"""add logs indexes

Revision ID: 344ef5ae1f5a
Revises: 4e52dca0e6ba
Create Date: 2026-03-01 15:13:52.588645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344ef5ae1f5a'
down_revision: Union[str, Sequence[str], None] = '4e52dca0e6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_logs_created_at', 'logs', ['created_at'], unique=False, schema='auth')
    op.create_index('ix_logs_user_id', 'logs', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_logs_user_id_created_at', 'logs', ['user_id', 'created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_user_id_created_at', table_name='logs', schema='auth')
    op.drop_index('ix_logs_user_id', table_name='logs', schema='auth')
    op.drop_index('ix_logs_created_at', table_name='logs', schema='auth')
    # ### end Alembic commands ###
