"""add composite logs user_id created_at index

Revision ID: 57a5a8070604
Revises: 5b2cb5a76a63
Create Date: 2026-03-01 21:22:35.142715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a5a8070604'
down_revision: Union[str, Sequence[str], None] = '5b2cb5a76a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_logs_user_id_created_at', 'logs', ['user_id', 'created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_logs_user_id_created_at', table_name='logs', schema='auth')
    # ### end Alembic commands ###
