"""simplify log indexes to index true

Revision ID: 5b2cb5a76a63
Revises: deea98246d63
Create Date: 2026-03-01 21:21:39.293989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2cb5a76a63'
down_revision: Union[str, Sequence[str], None] = 'deea98246d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs', schema='auth')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs', schema='auth')
    op.drop_index(op.f('ix_logs_user_id_created_at'), table_name='logs', schema='auth')
    op.create_index(op.f('ix_auth_logs_created_at'), 'logs', ['created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_logs_user_id'), 'logs', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_logs_user_id'), table_name='logs', schema='auth')
    op.drop_index(op.f('ix_auth_logs_created_at'), table_name='logs', schema='auth')
    op.create_index(op.f('ix_logs_user_id_created_at'), 'logs', ['user_id', 'created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###
