"""empty message

Revision ID: 6aab7889025f
Revises: e9b4c7a1d2f3
Create Date: 2026-03-01 21:07:59.625403

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aab7889025f"
down_revision: Union[str, Sequence[str], None] = "e9b4c7a1d2f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        schema="auth",
    )
    op.alter_column("users", "is_superuser", server_default=None, schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser", schema="auth")
    # ### end Alembic commands ###
