"""switch rbac fk indexes to index true

Revision ID: 8b0da812b7c1
Revises: 9161b8e679b0
Create Date: 2026-03-01 21:16:28.014162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0da812b7c1'
down_revision: Union[str, Sequence[str], None] = '9161b8e679b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions', schema='auth')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions', schema='auth')
    op.create_index(op.f('ix_auth_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles', schema='auth')
    op.create_index(op.f('ix_auth_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_user_id'), 'user_roles', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_roles_user_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_role_id'), table_name='user_roles', schema='auth')
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_auth_role_permissions_role_id'), table_name='role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_role_permissions_permission_id'), table_name='role_permissions', schema='auth')
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False, schema='auth')
    # ### end Alembic commands ###
