"""add indexes for role and permission created_at

Revision ID: deea98246d63
Revises: 8b0da812b7c1
Create Date: 2026-03-01 21:19:29.929729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deea98246d63'
down_revision: Union[str, Sequence[str], None] = '8b0da812b7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_permissions_created_at'), 'permissions', ['created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_roles_created_at'), 'roles', ['created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_roles_created_at'), table_name='roles', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_created_at'), table_name='permissions', schema='auth')
    # ### end Alembic commands ###
