"""init db schema

Revision ID: e557b1602158
Revises: 
Create Date: 2026-03-02 19:49:37.163588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e557b1602158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti'),
    schema='auth'
    )
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_logs_created_at'), 'logs', ['created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_logs_user_id'), 'logs', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_auth_logs_user_id_created_at', 'logs', ['user_id', 'created_at'], unique=False, schema='auth')
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_created_at'), 'permissions', ['created_at'], unique=False, schema='auth')
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_roles_created_at'), 'roles', ['created_at'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='auth'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False, schema='auth')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_user_id'), 'user_roles', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_roles_user_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_role_id'), table_name='user_roles', schema='auth')
    op.drop_table('user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_role_permissions_role_id'), table_name='role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_role_permissions_permission_id'), table_name='role_permissions', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_roles_created_at'), table_name='roles', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_created_at'), table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index('ix_auth_logs_user_id_created_at', table_name='logs', schema='auth')
    op.drop_index(op.f('ix_auth_logs_user_id'), table_name='logs', schema='auth')
    op.drop_index(op.f('ix_auth_logs_created_at'), table_name='logs', schema='auth')
    op.drop_table('logs', schema='auth')
    op.drop_table('blacklisted_tokens', schema='auth')
    # ### end Alembic commands ###
