[project]
name = "async_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "elasticsearch[async]>=9.2.1",
    "fastapi>=0.128.0",
    "orjson>=3.11.5",
    "redis>=7.1.0",
    "rich>=14.2.0",
    "uvicorn>=0.40.0",
]

