server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;

    location @movies_admin {
        proxy_pass http://movies-admin:8000;
    }

    location ^~ /static/ {
        alias /opt/movies_admin/static/;
        expires 90d;
    }

    location /admin {
        proxy_pass http://movies-admin:8000;
    }

    location /api {
        proxy_pass http://movies-admin:8000;
    }

    location /elasticsearch {
        proxy_pass http://elasticsearch:9200;
    }

    location / {
        try_files $uri @movies_admin;
    }

    error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}